# SPDX-FileCopyrightText: Copyright 2026 Daniel Balparda <balparda@github.com>
# SPDX-License-Identifier: Apache-2.0
"""func_timeout.exceptions minimal type stub."""

__version__ = ...
__version_tuple__ = ...
__all__ = ('FunctionTimedOut',)

class FunctionTimedOut(BaseException): ...
